// PhraseLexiconData.swift — FICHIER GÉNÉRÉ par eveil/outils/phrases/generer.py : ne pas modifier à la main.
//
// Le lexique du train des phrases (source : eveil/outils/phrases/lexique.py) : les noms
// (qui ? quoi ? où ?) et les verbes, en français et en anglais. Propositions, à valider
// avec le panel (docs/EVEIL.md § 8).

extension PhraseLexicon {
    public static let nouns: [PhraseNoun] = [
        PhraseNoun(id: "chat", drawing: "fr.minouche", gender: .masculine, fr: "chat", frIPA: "ʃa", en: "cat", enIPA: "kæt", roles: [.qui, .quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "chien", drawing: "fr.caniche", gender: .masculine, fr: "chien", frIPA: "ʃjɛ̃", en: "dog", enIPA: "dɔɡ", roles: [.qui, .quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "vache", drawing: "fr.vache", gender: .feminine, fr: "vache", frIPA: "vaʃ", en: "cow", enIPA: "kaʊ", roles: [.qui, .quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "biche", drawing: "fr.biche", gender: .feminine, fr: "biche", frIPA: "biʃ", en: "deer", enIPA: "dɪɹ", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "mouche", drawing: "fr.mouche", gender: .feminine, fr: "mouche", frIPA: "muʃ", en: "fly", enIPA: "flaɪ", roles: [.qui, .quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "oiseau", drawing: "fr.perruche", gender: .masculine, fr: "oiseau", frIPA: "wazo", en: "bird", enIPA: "bɝd", roles: [.qui, .quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "limace", drawing: "fr.limace", gender: .feminine, fr: "limace", frIPA: "limas", en: "slug", enIPA: "slʌɡ", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "autruche", drawing: "fr.autruche", gender: .feminine, fr: "autruche", frIPA: "otʁyʃ", en: "ostrich", enIPA: "ˈɑstɹɪtʃ", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "poisson", drawing: "en.fish", gender: .masculine, fr: "poisson", frIPA: "pwasɔ̃", en: "fish", enIPA: "fɪʃ", roles: [.qui, .quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "oie", drawing: "en.goose", gender: .feminine, fr: "oie", frIPA: "wa", en: "goose", enIPA: "ɡus", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "elan", drawing: "en.moose", gender: .masculine, fr: "élan", frIPA: "elɑ̃", en: "moose", enIPA: "mus", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "souris", drawing: "en.mouse", gender: .feminine, fr: "souris", frIPA: "suʁi", en: "mouse", enIPA: "maʊs", roles: [.qui, .quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "princesse", drawing: "fr.princesse", gender: .feminine, fr: "princesse", frIPA: "pʁɛ̃sɛs", en: "princess", enIPA: "ˈpɹɪnsɛs", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "lou", drawing: "perso.lou", gender: .proper, fr: "Lou", frIPA: "lu", en: "Lou", enIPA: "lu", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "peche", drawing: "fr.peche", gender: .feminine, fr: "pêche", frIPA: "pɛʃ", en: "peach", enIPA: "pitʃ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "saucisse", drawing: "fr.saucisse", gender: .feminine, fr: "saucisse", frIPA: "sosis", en: "sausage", enIPA: "ˈsɔsɪdʒ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "glace", drawing: "fr.glace", gender: .feminine, fr: "glace", frIPA: "ɡlas", en: "ice cream", enIPA: "ˈaɪs kɹim", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "os", drawing: "fr.os", gender: .masculine, fr: "os", frIPA: "ɔs", en: "bone", enIPA: "boʊn", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "radis", drawing: "en.radish", gender: .masculine, fr: "radis", frIPA: "ʁadi", en: "radish", enIPA: "ˈɹædɪʃ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "jus", drawing: "en.juice", gender: .masculine, fr: "jus", frIPA: "ʒy", en: "juice", enIPA: "dʒus", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "tasse", drawing: "fr.tasse", gender: .feminine, fr: "tasse", frIPA: "tas", en: "cup", enIPA: "kʌp", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "assiette", drawing: "en.dish", gender: .feminine, fr: "assiette", frIPA: "asjɛt", en: "plate", enIPA: "pleɪt", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "brosse", drawing: "fr.brosse", gender: .feminine, fr: "brosse", frIPA: "bʁɔs", en: "brush", enIPA: "bɹʌʃ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "cloche", drawing: "fr.cloche", gender: .feminine, fr: "cloche", frIPA: "klɔʃ", en: "bell", enIPA: "bɛl", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "trousse", drawing: "fr.trousse", gender: .feminine, fr: "trousse", frIPA: "tʁus", en: "pencil case", enIPA: "ˈpɛnsəl keɪs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "fleche", drawing: "fr.fleche", gender: .feminine, fr: "flèche", frIPA: "flɛʃ", en: "arrow", enIPA: "ˈæɹoʊ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "buche", drawing: "fr.buche", gender: .feminine, fr: "bûche", frIPA: "byʃ", en: "log", enIPA: "lɔɡ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "balle", drawing: "en.tennis", gender: .feminine, fr: "balle", frIPA: "bal", en: "ball", enIPA: "bɔl", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "bus", drawing: "en.bus", gender: .masculine, fr: "bus", frIPA: "bys", en: "bus", enIPA: "bʌs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "carrosse", drawing: "fr.carrosse", gender: .masculine, fr: "carrosse", frIPA: "kaʁɔs", en: "carriage", enIPA: "ˈkæɹɪdʒ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "boite", drawing: "lieu.boite", gender: .feminine, fr: "boîte", frIPA: "bwat", en: "box", enIPA: "bɑks", roles: [.ou], facesLeft: false, prepositions: ["dans", "sur", "devant", "derriere"]),
        PhraseNoun(id: "niche", drawing: "lieu.niche", gender: .feminine, fr: "niche", frIPA: "niʃ", en: "doghouse", enIPA: "ˈdɔɡhaʊs", roles: [.ou], facesLeft: false, prepositions: ["dans", "sur", "devant", "derriere"]),
        PhraseNoun(id: "maison", drawing: "lieu.maison", gender: .feminine, fr: "maison", frIPA: "mɛzɔ̃", en: "house", enIPA: "haʊs", roles: [.ou], facesLeft: false, prepositions: ["dans", "sur", "devant", "derriere"]),
        PhraseNoun(id: "table", drawing: "lieu.table", gender: .feminine, fr: "table", frIPA: "tabl", en: "table", enIPA: "ˈteɪbəl", roles: [.ou], facesLeft: false, prepositions: ["sur", "sous", "devant", "derriere"]),
        PhraseNoun(id: "lit", drawing: "lieu.lit", gender: .masculine, fr: "lit", frIPA: "li", en: "bed", enIPA: "bɛd", roles: [.ou], facesLeft: false, prepositions: ["dans", "sur", "sous", "devant"]),
        PhraseNoun(id: "arbre", drawing: "lieu.arbre", gender: .masculine, fr: "arbre", frIPA: "aʁbʁ", en: "tree", enIPA: "tɹi", roles: [.ou], facesLeft: false, prepositions: ["dans", "sous", "devant", "derriere"]),
        PhraseNoun(id: "baignoire", drawing: "lieu.baignoire", gender: .feminine, fr: "baignoire", frIPA: "bɛɲwaʁ", en: "bathtub", enIPA: "ˈbæθtʌb", roles: [.ou], facesLeft: false, prepositions: ["dans", "devant", "derriere"]),
        PhraseNoun(id: "voiture", drawing: "lieu.voiture", gender: .feminine, fr: "voiture", frIPA: "vwatyʁ", en: "car", enIPA: "kɑɹ", roles: [.ou], facesLeft: false, prepositions: ["dans", "sur", "devant", "derriere"]),
        PhraseNoun(id: "fleur", drawing: "mot.fleur", gender: .feminine, fr: "fleur", frIPA: "flœʁ", en: "flower", enIPA: "ˈflaʊɚ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "fee", drawing: "mot.fee", gender: .feminine, fr: "fée", frIPA: "fe", en: "fairy", enIPA: "ˈfɛɹi", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "fusee", drawing: "mot.fusee", gender: .feminine, fr: "fusée", frIPA: "fyze", en: "rocket", enIPA: "ˈɹɑkɪt", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "fraise", drawing: "mot.fraise", gender: .feminine, fr: "fraise", frIPA: "fʁɛz", en: "strawberry", enIPA: "ˈstɹɔbɛɹi", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "fourchette", drawing: "mot.fourchette", gender: .feminine, fr: "fourchette", frIPA: "fuʁʃɛt", en: "fork", enIPA: "fɔɹk", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "phoque", drawing: "mot.phoque", gender: .masculine, fr: "phoque", frIPA: "fɔk", en: "seal", enIPA: "sil", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "girafe", drawing: "mot.girafe", gender: .feminine, fr: "girafe", frIPA: "ʒiʁaf", en: "giraffe", enIPA: "dʒəˈɹæf", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "velo", drawing: "mot.velo", gender: .masculine, fr: "vélo", frIPA: "velo", en: "bike", enIPA: "baɪk", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "verre", drawing: "mot.verre", gender: .masculine, fr: "verre", frIPA: "vɛʁ", en: "glass", enIPA: "ɡlæs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "valise", drawing: "mot.valise", gender: .feminine, fr: "valise", frIPA: "valiz", en: "suitcase", enIPA: "ˈsutkeɪs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "cheval", drawing: "mot.cheval", gender: .masculine, fr: "cheval", frIPA: "ʃəval", en: "horse", enIPA: "hɔɹs", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "jupe", drawing: "mot.jupe", gender: .feminine, fr: "jupe", frIPA: "ʒyp", en: "skirt", enIPA: "skɝt", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "orange", drawing: "mot.orange", gender: .feminine, fr: "orange", frIPA: "ɔʁɑ̃ʒ", en: "orange", enIPA: "ˈɔɹɪndʒ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "cage", drawing: "mot.cage", gender: .feminine, fr: "cage", frIPA: "kaʒ", en: "cage", enIPA: "keɪdʒ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "gateau", drawing: "mot.gateau", gender: .masculine, fr: "gâteau", frIPA: "ɡato", en: "cake", enIPA: "keɪk", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "gomme", drawing: "mot.gomme", gender: .feminine, fr: "gomme", frIPA: "ɡɔm", en: "eraser", enIPA: "ɪˈɹeɪsɚ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "guitare", drawing: "mot.guitare", gender: .feminine, fr: "guitare", frIPA: "ɡitaʁ", en: "guitar", enIPA: "ɡɪˈtɑɹ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "gant", drawing: "mot.gant", gender: .masculine, fr: "gant", frIPA: "ɡɑ̃", en: "glove", enIPA: "ɡlʌv", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "grenouille", drawing: "mot.grenouille", gender: .feminine, fr: "grenouille", frIPA: "ɡʁənuj", en: "frog", enIPA: "fɹɔɡ", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "bague", drawing: "mot.bague", gender: .feminine, fr: "bague", frIPA: "baɡ", en: "ring", enIPA: "ɹɪŋ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "dragon", drawing: "mot.dragon", gender: .masculine, fr: "dragon", frIPA: "dʁaɡɔ̃", en: "dragon", enIPA: "ˈdɹæɡən", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "dinosaure", drawing: "mot.dinosaure", gender: .masculine, fr: "dinosaure", frIPA: "dinozɔʁ", en: "dinosaur", enIPA: "ˈdaɪnəsɔɹ", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "de", drawing: "mot.de", gender: .masculine, fr: "dé", frIPA: "de", en: "dice", enIPA: "daɪs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "dauphin", drawing: "mot.dauphin", gender: .masculine, fr: "dauphin", frIPA: "dofɛ̃", en: "dolphin", enIPA: "ˈdɑlfɪn", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "coq", drawing: "mot.coq", gender: .masculine, fr: "coq", frIPA: "kɔk", en: "rooster", enIPA: "ˈɹustɚ", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "canard", drawing: "mot.canard", gender: .masculine, fr: "canard", frIPA: "kanaʁ", en: "duck", enIPA: "dʌk", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "cle", drawing: "mot.cle", gender: .feminine, fr: "clé", frIPA: "kle", en: "key", enIPA: "ki", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "camion", drawing: "mot.camion", gender: .masculine, fr: "camion", frIPA: "kamjɔ̃", en: "truck", enIPA: "tɹʌk", roles: [.quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "crocodile", drawing: "mot.crocodile", gender: .masculine, fr: "crocodile", frIPA: "kʁɔkɔdil", en: "crocodile", enIPA: "ˈkɹɑkədaɪl", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "cadeau", drawing: "mot.cadeau", gender: .masculine, fr: "cadeau", frIPA: "kado", en: "gift", enIPA: "ɡɪft", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "sac", drawing: "mot.sac", gender: .masculine, fr: "sac", frIPA: "sak", en: "bag", enIPA: "bæɡ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "zebre", drawing: "mot.zebre", gender: .masculine, fr: "zèbre", frIPA: "zɛbʁ", en: "zebra", enIPA: "ˈzibɹə", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "rose", drawing: "mot.rose", gender: .feminine, fr: "rose", frIPA: "ʁoz", en: "rose", enIPA: "ɹoʊz", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "vase", drawing: "mot.vase", gender: .masculine, fr: "vase", frIPA: "vaz", en: "vase", enIPA: "veɪs", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "ciseaux", drawing: "mot.ciseaux", gender: .plural, fr: "ciseaux", frIPA: "sizo", en: "scissors", enIPA: "ˈsɪzɚz", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "nid", drawing: "mot.nid", gender: .masculine, fr: "nid", frIPA: "ni", en: "nest", enIPA: "nɛst", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "banane", drawing: "mot.banane", gender: .feminine, fr: "banane", frIPA: "banan", en: "banana", enIPA: "bəˈnænə", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "pomme", drawing: "mot.pomme", gender: .feminine, fr: "pomme", frIPA: "pɔm", en: "apple", enIPA: "ˈæpəl", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "pain", drawing: "mot.pain", gender: .masculine, fr: "pain", frIPA: "pɛ̃", en: "bread", enIPA: "bɹɛd", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "papillon", drawing: "mot.papillon", gender: .masculine, fr: "papillon", frIPA: "papijɔ̃", en: "butterfly", enIPA: "ˈbʌtɚflaɪ", roles: [.qui, .quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "parapluie", drawing: "mot.parapluie", gender: .masculine, fr: "parapluie", frIPA: "paʁaplɥi", en: "umbrella", enIPA: "ʌmˈbɹɛlə", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "lapin", drawing: "mot.lapin", gender: .masculine, fr: "lapin", frIPA: "lapɛ̃", en: "rabbit", enIPA: "ˈɹæbɪt", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "soupe", drawing: "mot.soupe", gender: .feminine, fr: "soupe", frIPA: "sup", en: "soup", enIPA: "sup", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "moto", drawing: "mot.moto", gender: .feminine, fr: "moto", frIPA: "moto", en: "motorbike", enIPA: "ˈmoʊtɚbaɪk", roles: [.quoi], facesLeft: true, prepositions: []),
        PhraseNoun(id: "mouton", drawing: "mot.mouton", gender: .masculine, fr: "mouton", frIPA: "mutɔ̃", en: "sheep", enIPA: "ʃip", roles: [.qui], facesLeft: true, prepositions: []),
        PhraseNoun(id: "plume", drawing: "mot.plume", gender: .feminine, fr: "plume", frIPA: "plym", en: "feather", enIPA: "ˈfɛðɚ", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "araignee", drawing: "mot.araignee", gender: .feminine, fr: "araignée", frIPA: "aʁɛɲe", en: "spider", enIPA: "ˈspaɪdɚ", roles: [.qui], facesLeft: false, prepositions: []),
        PhraseNoun(id: "champignon", drawing: "mot.champignon", gender: .masculine, fr: "champignon", frIPA: "ʃɑ̃piɲɔ̃", en: "mushroom", enIPA: "ˈmʌʃɹum", roles: [.quoi], facesLeft: false, prepositions: []),
        PhraseNoun(id: "peigne", drawing: "mot.peigne", gender: .masculine, fr: "peigne", frIPA: "pɛɲ", en: "comb", enIPA: "koʊm", roles: [.quoi], facesLeft: false, prepositions: []),
    ]

    public static let verbs: [PhraseVerb] = [
        PhraseVerb(id: "dormir", fr: "dort", frIPA: "dɔʁ", en: "sleeps", enIPA: "slips", transitive: false, absolute: false, objects: [], prepositions: ["dans", "sur", "sous"], places: []),
        PhraseVerb(id: "sauter", fr: "saute", frIPA: "sot", en: "jumps", enIPA: "dʒʌmps", transitive: false, absolute: false, objects: [], prepositions: ["sur", "dans", "devant"], places: []),
        PhraseVerb(id: "danser", fr: "danse", frIPA: "dɑ̃s", en: "dances", enIPA: "ˈdænsɪz", transitive: false, absolute: false, objects: [], prepositions: ["sur", "devant", "dans"], places: []),
        PhraseVerb(id: "courir", fr: "court", frIPA: "kuʁ", en: "runs", enIPA: "ɹʌnz", transitive: false, absolute: false, objects: [], prepositions: ["devant", "derriere", "dans"], places: []),
        PhraseVerb(id: "chanter", fr: "chante", frIPA: "ʃɑ̃t", en: "sings", enIPA: "sɪŋz", transitive: false, absolute: false, objects: [], prepositions: ["dans", "sur", "devant", "sous"], places: []),
        PhraseVerb(id: "nager", fr: "nage", frIPA: "naʒ", en: "swims", enIPA: "swɪmz", transitive: false, absolute: false, objects: [], prepositions: ["dans"], places: ["baignoire"]),
        PhraseVerb(id: "voler", fr: "vole", frIPA: "vɔl", en: "flies", enIPA: "flaɪz", transitive: false, absolute: false, objects: [], prepositions: ["dans", "devant", "derriere", "sur"], places: []),
        PhraseVerb(id: "tourner", fr: "tourne", frIPA: "tuʁn", en: "spins", enIPA: "spɪnz", transitive: false, absolute: false, objects: [], prepositions: ["sur", "devant", "dans"], places: []),
        PhraseVerb(id: "rire", fr: "rit", frIPA: "ʁi", en: "laughs", enIPA: "læfs", transitive: false, absolute: false, objects: [], prepositions: ["dans", "sur", "sous", "devant", "derriere"], places: []),
        PhraseVerb(id: "se_cacher", fr: "se cache", frIPA: "sə kaʃ", en: "hides", enIPA: "haɪdz", transitive: false, absolute: false, objects: [], prepositions: ["dans", "sous", "derriere"], places: []),
        PhraseVerb(id: "manger", fr: "mange", frIPA: "mɑ̃ʒ", en: "eats", enIPA: "its", transitive: true, absolute: true, objects: ["peche", "saucisse", "glace", "os", "radis", "pomme", "banane", "fraise", "gateau", "pain", "orange", "champignon", "soupe"], prepositions: [], places: []),
        PhraseVerb(id: "boire", fr: "boit", frIPA: "bwa", en: "drinks", enIPA: "dɹɪŋks", transitive: true, absolute: true, objects: ["jus", "tasse", "soupe"], prepositions: [], places: []),
        PhraseVerb(id: "pousser", fr: "pousse", frIPA: "pus", en: "pushes", enIPA: "ˈpʊʃɪz", transitive: true, absolute: false, objects: ["bus", "carrosse", "buche", "trousse", "balle", "cloche", "camion", "velo", "valise", "cage", "moto", "cadeau", "fusee"], prepositions: [], places: []),
        PhraseVerb(id: "porter", fr: "porte", frIPA: "pɔʁt", en: "carries", enIPA: "ˈkæɹiz", transitive: true, absolute: false, objects: ["trousse", "buche", "os", "tasse", "cloche", "peche", "brosse", "valise", "sac", "cadeau", "parapluie", "guitare", "gateau", "vase", "cage", "fleur", "nid", "pain", "jupe", "bague", "gant", "ciseaux", "cle", "fusee", "fourchette", "verre", "peigne", "gomme"], prepositions: [], places: []),
        PhraseVerb(id: "lancer", fr: "lance", frIPA: "lɑ̃s", en: "throws", enIPA: "θɹoʊz", transitive: true, absolute: false, objects: ["balle", "os", "peche", "fleche", "brosse", "trousse", "de", "pomme", "orange", "plume", "gant", "cle", "gomme", "peigne"], prepositions: [], places: []),
        PhraseVerb(id: "laver", fr: "lave", frIPA: "lav", en: "washes", enIPA: "ˈwɑʃɪz", transitive: true, absolute: false, objects: ["tasse", "assiette", "chien", "vache", "bus", "brosse", "carrosse", "velo", "camion", "moto", "verre", "fourchette", "jupe", "gant", "peigne", "vase", "ciseaux", "bague"], prepositions: [], places: []),
        PhraseVerb(id: "attraper", fr: "attrape", frIPA: "atʁap", en: "catches", enIPA: "ˈkætʃɪz", transitive: true, absolute: false, objects: ["balle", "mouche", "os", "peche", "fleche", "papillon", "plume", "cle", "pomme", "orange", "de"], prepositions: [], places: []),
        PhraseVerb(id: "lecher", fr: "lèche", frIPA: "lɛʃ", en: "licks", enIPA: "lɪks", transitive: true, absolute: false, objects: ["glace", "os", "assiette", "chat", "fraise", "gateau"], prepositions: [], places: []),
        PhraseVerb(id: "sentir", fr: "sent", frIPA: "sɑ̃", en: "smells", enIPA: "smɛlz", transitive: true, absolute: false, objects: ["peche", "saucisse", "glace", "radis", "jus", "fleur", "rose", "fraise", "pomme", "orange", "gateau", "pain", "soupe", "champignon", "banane"], prepositions: [], places: []),
        PhraseVerb(id: "tirer", fr: "tire", frIPA: "tiʁ", en: "pulls", enIPA: "pʊlz", transitive: true, absolute: false, objects: ["carrosse", "bus", "buche", "trousse", "brosse", "camion", "velo", "valise", "sac", "cage", "moto", "parapluie"], prepositions: [], places: []),
    ]
}
