// SoundBooksData.swift — FICHIER GÉNÉRÉ par eveil/outils/livres/generer.py : ne pas modifier à la main.
//
// Les livres des sons : un livre par son, calculé à partir des mots dessinés (au début, au
// milieu, à la fin), avec le wagon du son et ses lettres ; une image sonore et une idée de jeu
// pour l'adulte (propositions à valider par des orthophonistes, docs/EVEIL.md § 8).
// EN COURS : 75 mots sur 103 ont déjà leur dessin ; les livres grandiront.

extension SoundBooks {
    public static let all: [SoundBook] = [
        SoundBook(locale: "fr-FR", sound: "ʃ", label: "ch",
                  image: "Le train à vapeur : chhh ! Les lèvres en avant, comme pour un bisou.",
                  game: "Jouez au train à vapeur au bain : chhh ! Puis cherchez dans la maison trois choses qui font « ch ».", words: [
                      SoundBookWord(id: "champignon", drawing: "mot.champignon", text: "champignon", ipa: "ʃɑ̃.pi.ɲɔ̃", wagons: ["cham", "pi", "gnon"], targetWagon: 0, letters: "ch", position: .start),
                      SoundBookWord(id: "chat", drawing: "fr.minouche", text: "chat", ipa: "ʃa", wagons: ["chat"], targetWagon: 0, letters: "ch", position: .start),
                      SoundBookWord(id: "chien", drawing: "fr.caniche", text: "chien", ipa: "ʃjɛ̃", wagons: ["chien"], targetWagon: 0, letters: "ch", position: .start),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "autruche", ipa: "o.tʁyʃ", wagons: ["au", "truche"], targetWagon: 1, letters: "ch", position: .end),
                      SoundBookWord(id: "biche", drawing: "fr.biche", text: "biche", ipa: "biʃ", wagons: ["biche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "bouche", drawing: "fr.bouche", text: "bouche", ipa: "buʃ", wagons: ["bouche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "buche", drawing: "fr.buche", text: "bûche", ipa: "byʃ", wagons: ["bûche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "cloche", drawing: "fr.cloche", text: "cloche", ipa: "klɔʃ", wagons: ["cloche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "douche", drawing: "fr.douche", text: "douche", ipa: "duʃ", wagons: ["douche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "fleche", drawing: "fr.fleche", text: "flèche", ipa: "flɛʃ", wagons: ["flèche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "mouche", drawing: "fr.mouche", text: "mouche", ipa: "muʃ", wagons: ["mouche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "niche", drawing: "lieu.niche", text: "niche", ipa: "niʃ", wagons: ["niche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "peche", drawing: "fr.peche", text: "pêche", ipa: "pɛʃ", wagons: ["pêche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "ruche", drawing: "fr.ruche", text: "ruche", ipa: "ʁyʃ", wagons: ["ruche"], targetWagon: 0, letters: "ch", position: .end),
                      SoundBookWord(id: "vache", drawing: "fr.vache", text: "vache", ipa: "vaʃ", wagons: ["vache"], targetWagon: 0, letters: "ch", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "s", label: "s",
                  image: "Le serpent : sss ! Les dents presque fermées, on siffle.",
                  game: "Faites le serpent qui glisse sur le tapis : sss ! Qui trouvera le plus de « s » dans la cuisine ?", words: [
                      SoundBookWord(id: "cirque", drawing: "en.circus", text: "cirque", ipa: "siʁk", wagons: ["cirque"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "ciseaux", drawing: "mot.ciseaux", text: "ciseaux", ipa: "si.zo", wagons: ["ci", "seaux"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "sac", drawing: "mot.sac", text: "sac", ipa: "sak", wagons: ["sac"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "saucisse", drawing: "fr.saucisse", text: "saucisse", ipa: "so.sis", wagons: ["sau", "cisse"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "soupe", drawing: "mot.soupe", text: "soupe", ipa: "sup", wagons: ["soupe"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "souris", drawing: "en.mouse", text: "souris", ipa: "su.ʁi", wagons: ["sou", "ris"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "assiette", drawing: "en.dish", text: "assiette", ipa: "a.sjɛt", wagons: ["a", "ssiette"], targetWagon: 1, letters: "ss", position: .middle),
                      SoundBookWord(id: "glacon", drawing: "en.ice", text: "glaçon", ipa: "ɡla.sɔ̃", wagons: ["gla", "çon"], targetWagon: 1, letters: "ç", position: .middle),
                      SoundBookWord(id: "poisson", drawing: "en.fish", text: "poisson", ipa: "pwa.sɔ̃", wagons: ["pois", "son"], targetWagon: 1, letters: "s", position: .middle),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princesse", ipa: "pʁɛ̃.sɛs", wagons: ["prin", "cesse"], targetWagon: 1, letters: "ss", position: .middle),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brosse", ipa: "bʁɔs", wagons: ["brosse"], targetWagon: 0, letters: "ss", position: .end),
                      SoundBookWord(id: "bus", drawing: "en.bus", text: "bus", ipa: "bys", wagons: ["bus"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "kak.tys", wagons: ["cac", "tus"], targetWagon: 1, letters: "s", position: .end),
                      SoundBookWord(id: "carrosse", drawing: "fr.carrosse", text: "carrosse", ipa: "ka.ʁɔs", wagons: ["ca", "rrosse"], targetWagon: 1, letters: "ss", position: .end),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "glace", ipa: "ɡlas", wagons: ["glace"], targetWagon: 0, letters: "c", position: .end),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "limace", ipa: "li.mas", wagons: ["li", "mace"], targetWagon: 1, letters: "c", position: .end),
                      SoundBookWord(id: "os", drawing: "fr.os", text: "os", ipa: "ɔs", wagons: ["os"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police", ipa: "pɔ.lis", wagons: ["po", "lice"], targetWagon: 1, letters: "c", position: .end),
                      SoundBookWord(id: "tasse", drawing: "fr.tasse", text: "tasse", ipa: "tas", wagons: ["tasse"], targetWagon: 0, letters: "ss", position: .end),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "trousse", ipa: "tʁus", wagons: ["trousse"], targetWagon: 0, letters: "ss", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "z", label: "z",
                  image: "L'abeille : zzz ! Comme le serpent, mais la gorge vibre (posez la main dessus).",
                  game: "L'abeille vole de fleur en fleur : zzz… et se pose sur le nez de quelqu'un !", words: [
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zèbre", ipa: "zɛbʁ", wagons: ["zèbre"], targetWagon: 0, letters: "z", position: .start),
                      SoundBookWord(id: "ciseaux", drawing: "mot.ciseaux", text: "ciseaux", ipa: "si.zo", wagons: ["ci", "seaux"], targetWagon: 1, letters: "s", position: .middle),
                      SoundBookWord(id: "maison", drawing: "lieu.maison", text: "maison", ipa: "mɛ.zɔ̃", wagons: ["mai", "son"], targetWagon: 1, letters: "s", position: .middle),
                      SoundBookWord(id: "oiseau", drawing: "fr.perruche", text: "oiseau", ipa: "wa.zo", wagons: ["oi", "seau"], targetWagon: 1, letters: "s", position: .middle),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "pœzl", wagons: ["puzzle"], targetWagon: 0, letters: "zz", position: .middle),
                      SoundBookWord(id: "rose", drawing: "mot.rose", text: "rose", ipa: "ʁoz", wagons: ["rose"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "vase", drawing: "mot.vase", text: "vase", ipa: "vaz", wagons: ["vase"], targetWagon: 0, letters: "s", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "p", label: "p",
                  image: "Les bulles qui éclatent : p, p, p ! Les lèvres fermées, puis pouf !",
                  game: "Faites des bulles de savon et éclatez-les en disant « p ! » à chaque fois.", words: [
                      SoundBookWord(id: "pain", drawing: "mot.pain", text: "pain", ipa: "pɛ̃", wagons: ["pain"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "papillon", drawing: "mot.papillon", text: "papillon", ipa: "pa.pi.jɔ̃", wagons: ["pa", "pi", "llon"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "parapluie", ipa: "pa.ʁa.plɥi", wagons: ["pa", "ra", "pluie"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "peche", drawing: "fr.peche", text: "pêche", ipa: "pɛʃ", wagons: ["pêche"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "peigne", drawing: "mot.peigne", text: "peigne", ipa: "pɛɲ", wagons: ["peigne"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "plume", drawing: "mot.plume", text: "plume", ipa: "plym", wagons: ["plume"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "poisson", drawing: "en.fish", text: "poisson", ipa: "pwa.sɔ̃", wagons: ["pois", "son"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police", ipa: "pɔ.lis", wagons: ["po", "lice"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "pomme", drawing: "mot.pomme", text: "pomme", ipa: "pɔm", wagons: ["pomme"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princesse", ipa: "pʁɛ̃.sɛs", wagons: ["prin", "cesse"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "pœzl", wagons: ["puzzle"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "champignon", drawing: "mot.champignon", text: "champignon", ipa: "ʃɑ̃.pi.ɲɔ̃", wagons: ["cham", "pi", "gnon"], targetWagon: 1, letters: "p", position: .middle),
                      SoundBookWord(id: "lapin", drawing: "mot.lapin", text: "lapin", ipa: "la.pɛ̃", wagons: ["la", "pin"], targetWagon: 1, letters: "p", position: .middle),
                      SoundBookWord(id: "soupe", drawing: "mot.soupe", text: "soupe", ipa: "sup", wagons: ["soupe"], targetWagon: 0, letters: "p", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "b", label: "b",
                  image: "Le poisson qui fait des bulles : b, b, b ! Les lèvres fermées, la gorge vibre.",
                  game: "Faites le poisson : joues gonflées, puis b, b, b !", words: [
                      SoundBookWord(id: "baignoire", drawing: "lieu.baignoire", text: "baignoire", ipa: "bɛ.ɲwaʁ", wagons: ["bai", "gnoire"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "balle", drawing: "en.tennis", text: "balle", ipa: "bal", wagons: ["balle"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "banane", drawing: "mot.banane", text: "banane", ipa: "ba.nan", wagons: ["ba", "nane"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "biche", drawing: "fr.biche", text: "biche", ipa: "biʃ", wagons: ["biche"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "boite", drawing: "lieu.boite", text: "boîte", ipa: "bwat", wagons: ["boîte"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "bouche", drawing: "fr.bouche", text: "bouche", ipa: "buʃ", wagons: ["bouche"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brosse", ipa: "bʁɔs", wagons: ["brosse"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "buche", drawing: "fr.buche", text: "bûche", ipa: "byʃ", wagons: ["bûche"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "bus", drawing: "en.bus", text: "bus", ipa: "bys", wagons: ["bus"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "arbre", drawing: "lieu.arbre", text: "arbre", ipa: "aʁbʁ", wagons: ["arbre"], targetWagon: 0, letters: "b", position: .middle),
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "tabl", wagons: ["table"], targetWagon: 0, letters: "b", position: .middle),
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zèbre", ipa: "zɛbʁ", wagons: ["zèbre"], targetWagon: 0, letters: "b", position: .middle),
                  ]),
        SoundBook(locale: "fr-FR", sound: "t", label: "t",
                  image: "L'horloge : tic-tac ! Le bout de la langue tape derrière les dents du haut.",
                  game: "Jouez à l'horloge : tic-tac, en balançant les bras, de plus en plus vite.", words: [
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "tabl", wagons: ["table"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "tasse", drawing: "fr.tasse", text: "tasse", ipa: "tas", wagons: ["tasse"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "trousse", ipa: "tʁus", wagons: ["trousse"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "autruche", ipa: "o.tʁyʃ", wagons: ["au", "truche"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "kak.tys", wagons: ["cac", "tus"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "moto", ipa: "mo.to", wagons: ["mo", "to"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "mouton", drawing: "mot.mouton", text: "mouton", ipa: "mu.tɔ̃", wagons: ["mou", "ton"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "voiture", drawing: "lieu.voiture", text: "voiture", ipa: "vwa.tyʁ", wagons: ["voi", "ture"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "assiette", drawing: "en.dish", text: "assiette", ipa: "a.sjɛt", wagons: ["a", "ssiette"], targetWagon: 1, letters: "tt", position: .end),
                      SoundBookWord(id: "boite", drawing: "lieu.boite", text: "boîte", ipa: "bwat", wagons: ["boîte"], targetWagon: 0, letters: "t", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "d", label: "d",
                  image: "Le tambour : dum, dum ! Comme « t », mais la gorge vibre.",
                  game: "Tapez sur une casserole en disant « dum, dum, dum ».", words: [
                      SoundBookWord(id: "dauphin", drawing: "mot.dauphin", text: "dauphin", ipa: "do.fɛ̃", wagons: ["dau", "phin"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "douche", drawing: "fr.douche", text: "douche", ipa: "duʃ", wagons: ["douche"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "cadeau", drawing: "mot.cadeau", text: "cadeau", ipa: "ka.do", wagons: ["ca", "deau"], targetWagon: 1, letters: "d", position: .middle),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "kʁɔ.kɔ.dil", wagons: ["cro", "co", "dile"], targetWagon: 2, letters: "d", position: .middle),
                      SoundBookWord(id: "radis", drawing: "en.radish", text: "radis", ipa: "ʁa.di", wagons: ["ra", "dis"], targetWagon: 1, letters: "d", position: .middle),
                  ]),
        SoundBook(locale: "fr-FR", sound: "k", label: "k",
                  image: "La poule : cot, cot, codec ! Le fond de la langue se ferme, puis s'ouvre.",
                  game: "Jouez à la poule qui cherche ses œufs : cot cot ! Cachez un objet, cot cot quand on s'en approche.", words: [
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "kak.tys", wagons: ["cac", "tus"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "cadeau", drawing: "mot.cadeau", text: "cadeau", ipa: "ka.do", wagons: ["ca", "deau"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "camion", drawing: "mot.camion", text: "camion", ipa: "ka.mjɔ̃", wagons: ["ca", "mion"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "canard", drawing: "mot.canard", text: "canard", ipa: "ka.naʁ", wagons: ["ca", "nard"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "carrosse", drawing: "fr.carrosse", text: "carrosse", ipa: "ka.ʁɔs", wagons: ["ca", "rrosse"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "cle", drawing: "mot.cle", text: "clé", ipa: "kle", wagons: ["clé"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "cloche", drawing: "fr.cloche", text: "cloche", ipa: "klɔʃ", wagons: ["cloche"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "coq", drawing: "mot.coq", text: "coq", ipa: "kɔk", wagons: ["coq"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "kʁɔ.kɔ.dil", wagons: ["cro", "co", "dile"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "cirque", drawing: "en.circus", text: "cirque", ipa: "siʁk", wagons: ["cirque"], targetWagon: 0, letters: "qu", position: .end),
                      SoundBookWord(id: "sac", drawing: "mot.sac", text: "sac", ipa: "sak", wagons: ["sac"], targetWagon: 0, letters: "c", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "m", label: "m",
                  image: "C'est bon : mmm ! Les lèvres fermées, ça chatouille.",
                  game: "Au repas, dites « mmm » après chaque bouchée préférée.", words: [
                      SoundBookWord(id: "maison", drawing: "lieu.maison", text: "maison", ipa: "mɛ.zɔ̃", wagons: ["mai", "son"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "moto", ipa: "mo.to", wagons: ["mo", "to"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "mouche", drawing: "fr.mouche", text: "mouche", ipa: "muʃ", wagons: ["mouche"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "mouton", drawing: "mot.mouton", text: "mouton", ipa: "mu.tɔ̃", wagons: ["mou", "ton"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "camion", drawing: "mot.camion", text: "camion", ipa: "ka.mjɔ̃", wagons: ["ca", "mion"], targetWagon: 1, letters: "m", position: .middle),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "limace", ipa: "li.mas", wagons: ["li", "mace"], targetWagon: 1, letters: "m", position: .middle),
                      SoundBookWord(id: "plume", drawing: "mot.plume", text: "plume", ipa: "plym", wagons: ["plume"], targetWagon: 0, letters: "m", position: .end),
                      SoundBookWord(id: "pomme", drawing: "mot.pomme", text: "pomme", ipa: "pɔm", wagons: ["pomme"], targetWagon: 0, letters: "mm", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "n", label: "n",
                  image: "Le nez qui vibre : nnn ! La langue derrière les dents, l'air passe par le nez.",
                  game: "Pincez-vous doucement le nez en faisant nnn : ça s'arrête ! Qu'est-ce qui se passe ?", words: [
                      SoundBookWord(id: "nez", drawing: "mot.nez", text: "nez", ipa: "ne", wagons: ["nez"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "niche", drawing: "lieu.niche", text: "niche", ipa: "niʃ", wagons: ["niche"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "nid", drawing: "mot.nid", text: "nid", ipa: "ni", wagons: ["nid"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "nuage", drawing: "mot.nuage", text: "nuage", ipa: "nɥaʒ", wagons: ["nuage"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "banane", drawing: "mot.banane", text: "banane", ipa: "ba.nan", wagons: ["ba", "nane"], targetWagon: 1, letters: "n", position: .middle),
                      SoundBookWord(id: "canard", drawing: "mot.canard", text: "canard", ipa: "ka.naʁ", wagons: ["ca", "nard"], targetWagon: 1, letters: "n", position: .middle),
                      SoundBookWord(id: "lune", drawing: "mot.lune", text: "lune", ipa: "lyn", wagons: ["lune"], targetWagon: 0, letters: "n", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "l", label: "l",
                  image: "On chante « la, la, la » : la langue se lève derrière les dents du haut.",
                  game: "Chantez une comptine sur « la, la, la », puis « lo, lo, lo », « li, li, li ».", words: [
                      SoundBookWord(id: "lapin", drawing: "mot.lapin", text: "lapin", ipa: "la.pɛ̃", wagons: ["la", "pin"], targetWagon: 0, letters: "l", position: .start),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "limace", ipa: "li.mas", wagons: ["li", "mace"], targetWagon: 0, letters: "l", position: .start),
                      SoundBookWord(id: "lit", drawing: "lieu.lit", text: "lit", ipa: "li", wagons: ["lit"], targetWagon: 0, letters: "l", position: .start),
                      SoundBookWord(id: "lou", drawing: "perso.lou", text: "Lou", ipa: "lu", wagons: ["Lou"], targetWagon: 0, letters: "L", position: .start),
                      SoundBookWord(id: "lune", drawing: "mot.lune", text: "lune", ipa: "lyn", wagons: ["lune"], targetWagon: 0, letters: "l", position: .start),
                      SoundBookWord(id: "cle", drawing: "mot.cle", text: "clé", ipa: "kle", wagons: ["clé"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "cloche", drawing: "fr.cloche", text: "cloche", ipa: "klɔʃ", wagons: ["cloche"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "elan", drawing: "en.moose", text: "élan", ipa: "e.lɑ̃", wagons: ["é", "lan"], targetWagon: 1, letters: "l", position: .middle),
                      SoundBookWord(id: "fleche", drawing: "fr.fleche", text: "flèche", ipa: "flɛʃ", wagons: ["flèche"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "glace", ipa: "ɡlas", wagons: ["glace"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "glacon", drawing: "en.ice", text: "glaçon", ipa: "ɡla.sɔ̃", wagons: ["gla", "çon"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "parapluie", ipa: "pa.ʁa.plɥi", wagons: ["pa", "ra", "pluie"], targetWagon: 2, letters: "l", position: .middle),
                      SoundBookWord(id: "plume", drawing: "mot.plume", text: "plume", ipa: "plym", wagons: ["plume"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police", ipa: "pɔ.lis", wagons: ["po", "lice"], targetWagon: 1, letters: "l", position: .middle),
                      SoundBookWord(id: "balle", drawing: "en.tennis", text: "balle", ipa: "bal", wagons: ["balle"], targetWagon: 0, letters: "ll", position: .end),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "kʁɔ.kɔ.dil", wagons: ["cro", "co", "dile"], targetWagon: 2, letters: "l", position: .end),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "pœzl", wagons: ["puzzle"], targetWagon: 0, letters: "l", position: .end),
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "tabl", wagons: ["table"], targetWagon: 0, letters: "l", position: .end),
                  ]),
        SoundBook(locale: "fr-FR", sound: "ʁ", label: "r",
                  image: "Le lion qui grogne : rrr ! Au fond de la gorge.",
                  game: "Jouez au lion qui se réveille : rrr doucement, puis plus fort.", words: [
                      SoundBookWord(id: "radis", drawing: "en.radish", text: "radis", ipa: "ʁa.di", wagons: ["ra", "dis"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "rose", drawing: "mot.rose", text: "rose", ipa: "ʁoz", wagons: ["rose"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "ruche", drawing: "fr.ruche", text: "ruche", ipa: "ʁyʃ", wagons: ["ruche"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "araignee", drawing: "mot.araignee", text: "araignée", ipa: "a.ʁɛ.ɲe", wagons: ["a", "rai", "gnée"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "arbre", drawing: "lieu.arbre", text: "arbre", ipa: "aʁbʁ", wagons: ["arbre"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "autruche", ipa: "o.tʁyʃ", wagons: ["au", "truche"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brosse", ipa: "bʁɔs", wagons: ["brosse"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "carrosse", drawing: "fr.carrosse", text: "carrosse", ipa: "ka.ʁɔs", wagons: ["ca", "rrosse"], targetWagon: 1, letters: "rr", position: .middle),
                      SoundBookWord(id: "cirque", drawing: "en.circus", text: "cirque", ipa: "siʁk", wagons: ["cirque"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "kʁɔ.kɔ.dil", wagons: ["cro", "co", "dile"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "parapluie", ipa: "pa.ʁa.plɥi", wagons: ["pa", "ra", "pluie"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princesse", ipa: "pʁɛ̃.sɛs", wagons: ["prin", "cesse"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "souris", drawing: "en.mouse", text: "souris", ipa: "su.ʁi", wagons: ["sou", "ris"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "trousse", ipa: "tʁus", wagons: ["trousse"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "baignoire", drawing: "lieu.baignoire", text: "baignoire", ipa: "bɛ.ɲwaʁ", wagons: ["bai", "gnoire"], targetWagon: 1, letters: "r", position: .end),
                      SoundBookWord(id: "canard", drawing: "mot.canard", text: "canard", ipa: "ka.naʁ", wagons: ["ca", "nard"], targetWagon: 1, letters: "r", position: .end),
                      SoundBookWord(id: "voiture", drawing: "lieu.voiture", text: "voiture", ipa: "vwa.tyʁ", wagons: ["voi", "ture"], targetWagon: 1, letters: "r", position: .end),
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zèbre", ipa: "zɛbʁ", wagons: ["zèbre"], targetWagon: 0, letters: "r", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "ʃ", label: "sh",
                  image: "The steam train: shhh! Lips forward, like a kiss.",
                  game: "Play steam trains in the bath: shhh! Then find three things at home with “sh”.", words: [
                      SoundBookWord(id: "mouton", drawing: "mot.mouton", text: "sheep", ipa: "ʃip", wagons: ["sheep"], targetWagon: 0, letters: "sh", position: .start),
                      SoundBookWord(id: "douche", drawing: "fr.douche", text: "shower", ipa: "ˈʃaʊ.ɚ", wagons: ["show", "er"], targetWagon: 0, letters: "sh", position: .start),
                      SoundBookWord(id: "champignon", drawing: "mot.champignon", text: "mushroom", ipa: "ˈmʌʃ.ɹum", wagons: ["mush", "room"], targetWagon: 0, letters: "sh", position: .middle),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brush", ipa: "bɹʌʃ", wagons: ["brush"], targetWagon: 0, letters: "sh", position: .end),
                      SoundBookWord(id: "poisson", drawing: "en.fish", text: "fish", ipa: "fɪʃ", wagons: ["fish"], targetWagon: 0, letters: "sh", position: .end),
                      SoundBookWord(id: "radis", drawing: "en.radish", text: "radish", ipa: "ˈɹæ.dɪʃ", wagons: ["ra", "dish"], targetWagon: 1, letters: "sh", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "s", label: "s",
                  image: "The snake: sss! Teeth almost closed, a gentle hiss.",
                  game: "Be snakes sliding on the rug: sss! Who finds the most “s” things in the kitchen?", words: [
                      SoundBookWord(id: "cirque", drawing: "en.circus", text: "circus", ipa: "ˈsɝ.kəs", wagons: ["cir", "cus"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "saucisse", drawing: "fr.saucisse", text: "sausage", ipa: "ˈsɔ.sɪdʒ", wagons: ["sau", "sage"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "ciseaux", drawing: "mot.ciseaux", text: "scissors", ipa: "ˈsɪ.zɚz", wagons: ["scis", "sors"], targetWagon: 0, letters: "sc", position: .start),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "slug", ipa: "slʌɡ", wagons: ["slug"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "soupe", drawing: "mot.soupe", text: "soup", ipa: "sup", wagons: ["soup"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "araignee", drawing: "mot.araignee", text: "spider", ipa: "ˈspaɪ.dɚ", wagons: ["spi", "der"], targetWagon: 0, letters: "s", position: .start),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "ice cream", ipa: "ˈaɪs.kɹim", wagons: ["ice", "cream"], targetWagon: 0, letters: "c", position: .middle),
                      SoundBookWord(id: "nid", drawing: "mot.nid", text: "nest", ipa: "nɛst", wagons: ["nest"], targetWagon: 0, letters: "s", position: .middle),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "ostrich", ipa: "ˈɑ.stɹɪtʃ", wagons: ["os", "trich"], targetWagon: 1, letters: "c", position: .middle),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "pencil case", ipa: "ˈpɛn.səl.keɪs", wagons: ["pen", "cil", "case"], targetWagon: 1, letters: "c", position: .middle),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police car", ipa: "pə.ˈlis.kɑɹ", wagons: ["po", "lice", "car"], targetWagon: 1, letters: "c", position: .middle),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princess", ipa: "ˈpɹɪn.sɛs", wagons: ["prin", "cess"], targetWagon: 1, letters: "ss", position: .middle),
                      SoundBookWord(id: "coq", drawing: "mot.coq", text: "rooster", ipa: "ˈɹus.tɚ", wagons: ["roos", "ter"], targetWagon: 0, letters: "s", position: .middle),
                      SoundBookWord(id: "boite", drawing: "lieu.boite", text: "box", ipa: "bɑks", wagons: ["box"], targetWagon: 0, letters: "x", position: .end),
                      SoundBookWord(id: "bus", drawing: "en.bus", text: "bus", ipa: "bʌs", wagons: ["bus"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "ˈkæk.təs", wagons: ["cac", "tus"], targetWagon: 1, letters: "s", position: .end),
                      SoundBookWord(id: "niche", drawing: "lieu.niche", text: "doghouse", ipa: "ˈdɔɡ.haʊs", wagons: ["dog", "house"], targetWagon: 1, letters: "s", position: .end),
                      SoundBookWord(id: "oie", drawing: "en.goose", text: "goose", ipa: "ɡus", wagons: ["goose"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "maison", drawing: "lieu.maison", text: "house", ipa: "haʊs", wagons: ["house"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "glacon", drawing: "en.ice", text: "ice", ipa: "aɪs", wagons: ["ice"], targetWagon: 0, letters: "c", position: .end),
                      SoundBookWord(id: "jus", drawing: "en.juice", text: "juice", ipa: "dʒus", wagons: ["juice"], targetWagon: 0, letters: "c", position: .end),
                      SoundBookWord(id: "elan", drawing: "en.moose", text: "moose", ipa: "mus", wagons: ["moose"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "souris", drawing: "en.mouse", text: "mouse", ipa: "maʊs", wagons: ["mouse"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "vase", drawing: "mot.vase", text: "vase", ipa: "veɪs", wagons: ["vase"], targetWagon: 0, letters: "s", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "z", label: "z",
                  image: "The bee: zzz! Like the snake, but the throat buzzes (feel it with a hand).",
                  game: "The bee flies from flower to flower: zzz… and lands on someone's nose!", words: [
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zebra", ipa: "ˈzi.bɹə", wagons: ["ze", "bra"], targetWagon: 0, letters: "z", position: .start),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "ˈpʌ.zəl", wagons: ["puz", "zle"], targetWagon: 1, letters: "z", position: .middle),
                      SoundBookWord(id: "ciseaux", drawing: "mot.ciseaux", text: "scissors", ipa: "ˈsɪ.zɚz", wagons: ["scis", "sors"], targetWagon: 1, letters: "s", position: .middle),
                      SoundBookWord(id: "nez", drawing: "mot.nez", text: "nose", ipa: "noʊz", wagons: ["nose"], targetWagon: 0, letters: "s", position: .end),
                      SoundBookWord(id: "rose", drawing: "mot.rose", text: "rose", ipa: "ɹoʊz", wagons: ["rose"], targetWagon: 0, letters: "s", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "f", label: "f",
                  image: "Blow out the candle: fff! Top teeth on the bottom lip.",
                  game: "Blow a feather or a paper ball together: fff! Who makes it go furthest?", words: [
                      SoundBookWord(id: "plume", drawing: "mot.plume", text: "feather", ipa: "ˈfɛ.ðɚ", wagons: ["fea", "ther"], targetWagon: 0, letters: "f", position: .start),
                      SoundBookWord(id: "poisson", drawing: "en.fish", text: "fish", ipa: "fɪʃ", wagons: ["fish"], targetWagon: 0, letters: "f", position: .start),
                      SoundBookWord(id: "mouche", drawing: "fr.mouche", text: "fly", ipa: "flaɪ", wagons: ["fly"], targetWagon: 0, letters: "f", position: .start),
                      SoundBookWord(id: "papillon", drawing: "mot.papillon", text: "butterfly", ipa: "ˈbʌ.tɚ.flaɪ", wagons: ["but", "ter", "fly"], targetWagon: 2, letters: "f", position: .middle),
                      SoundBookWord(id: "dauphin", drawing: "mot.dauphin", text: "dolphin", ipa: "ˈdɑl.fɪn", wagons: ["dol", "phin"], targetWagon: 1, letters: "ph", position: .middle),
                      SoundBookWord(id: "cadeau", drawing: "mot.cadeau", text: "gift", ipa: "ɡɪft", wagons: ["gift"], targetWagon: 0, letters: "f", position: .middle),
                  ]),
        SoundBook(locale: "en-US", sound: "p", label: "p",
                  image: "Popping bubbles: p, p, p! Lips closed, then pop!",
                  game: "Blow soap bubbles and pop each one with a “p!”.", words: [
                      SoundBookWord(id: "peche", drawing: "fr.peche", text: "peach", ipa: "pitʃ", wagons: ["peach"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "pencil case", ipa: "ˈpɛn.səl.keɪs", wagons: ["pen", "cil", "case"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "assiette", drawing: "en.dish", text: "plate", ipa: "pleɪt", wagons: ["plate"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police car", ipa: "pə.ˈlis.kɑɹ", wagons: ["po", "lice", "car"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princess", ipa: "ˈpɹɪn.sɛs", wagons: ["prin", "cess"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "ˈpʌ.zəl", wagons: ["puz", "zle"], targetWagon: 0, letters: "p", position: .start),
                      SoundBookWord(id: "pomme", drawing: "mot.pomme", text: "apple", ipa: "ˈæ.pəl", wagons: ["ap", "ple"], targetWagon: 1, letters: "p", position: .middle),
                      SoundBookWord(id: "araignee", drawing: "mot.araignee", text: "spider", ipa: "ˈspaɪ.dɚ", wagons: ["spi", "der"], targetWagon: 0, letters: "p", position: .middle),
                      SoundBookWord(id: "tasse", drawing: "fr.tasse", text: "cup", ipa: "kʌp", wagons: ["cup"], targetWagon: 0, letters: "p", position: .end),
                      SoundBookWord(id: "mouton", drawing: "mot.mouton", text: "sheep", ipa: "ʃip", wagons: ["sheep"], targetWagon: 0, letters: "p", position: .end),
                      SoundBookWord(id: "soupe", drawing: "mot.soupe", text: "soup", ipa: "sup", wagons: ["soup"], targetWagon: 0, letters: "p", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "b", label: "b",
                  image: "The fish blowing bubbles: b, b, b! Lips closed, throat buzzing.",
                  game: "Be fish: puffed cheeks, then b, b, b!", words: [
                      SoundBookWord(id: "sac", drawing: "mot.sac", text: "bag", ipa: "bæɡ", wagons: ["bag"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "balle", drawing: "en.tennis", text: "ball", ipa: "bɔl", wagons: ["ball"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "banane", drawing: "mot.banane", text: "banana", ipa: "bə.ˈnæ.nə", wagons: ["ba", "na", "na"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "baignoire", drawing: "lieu.baignoire", text: "bathtub", ipa: "ˈbæθ.tʌb", wagons: ["bath", "tub"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "lit", drawing: "lieu.lit", text: "bed", ipa: "bɛd", wagons: ["bed"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "ruche", drawing: "fr.ruche", text: "beehive", ipa: "ˈbi.haɪv", wagons: ["bee", "hive"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "cloche", drawing: "fr.cloche", text: "bell", ipa: "bɛl", wagons: ["bell"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "oiseau", drawing: "fr.perruche", text: "bird", ipa: "bɝd", wagons: ["bird"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "os", drawing: "fr.os", text: "bone", ipa: "boʊn", wagons: ["bone"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "boite", drawing: "lieu.boite", text: "box", ipa: "bɑks", wagons: ["box"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "pain", drawing: "mot.pain", text: "bread", ipa: "bɹɛd", wagons: ["bread"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brush", ipa: "bɹʌʃ", wagons: ["brush"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "bus", drawing: "en.bus", text: "bus", ipa: "bʌs", wagons: ["bus"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "papillon", drawing: "mot.papillon", text: "butterfly", ipa: "ˈbʌ.tɚ.flaɪ", wagons: ["but", "ter", "fly"], targetWagon: 0, letters: "b", position: .start),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "motorbike", ipa: "ˈmoʊ.tɚ.baɪk", wagons: ["mo", "tor", "bike"], targetWagon: 2, letters: "b", position: .middle),
                      SoundBookWord(id: "lapin", drawing: "mot.lapin", text: "rabbit", ipa: "ˈɹæ.bɪt", wagons: ["rab", "bit"], targetWagon: 1, letters: "b", position: .middle),
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "ˈteɪ.bəl", wagons: ["ta", "ble"], targetWagon: 1, letters: "b", position: .middle),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "umbrella", ipa: "ʌm.ˈbɹɛ.lə", wagons: ["um", "brel", "la"], targetWagon: 1, letters: "b", position: .middle),
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zebra", ipa: "ˈzi.bɹə", wagons: ["ze", "bra"], targetWagon: 1, letters: "b", position: .middle),
                  ]),
        SoundBook(locale: "en-US", sound: "t", label: "t",
                  image: "The clock: tick-tock! The tongue tip taps behind the top teeth.",
                  game: "Play clocks: tick-tock, swinging your arms, faster and faster.", words: [
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "ˈteɪ.bəl", wagons: ["ta", "ble"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "arbre", drawing: "lieu.arbre", text: "tree", ipa: "tɹi", wagons: ["tree"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "camion", drawing: "mot.camion", text: "truck", ipa: "tɹʌk", wagons: ["truck"], targetWagon: 0, letters: "t", position: .start),
                      SoundBookWord(id: "baignoire", drawing: "lieu.baignoire", text: "bathtub", ipa: "ˈbæθ.tʌb", wagons: ["bath", "tub"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "papillon", drawing: "mot.papillon", text: "butterfly", ipa: "ˈbʌ.tɚ.flaɪ", wagons: ["but", "ter", "fly"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "ˈkæk.təs", wagons: ["cac", "tus"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "motorbike", ipa: "ˈmoʊ.tɚ.baɪk", wagons: ["mo", "tor", "bike"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "ostrich", ipa: "ˈɑ.stɹɪtʃ", wagons: ["os", "trich"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "coq", drawing: "mot.coq", text: "rooster", ipa: "ˈɹus.tɚ", wagons: ["roos", "ter"], targetWagon: 1, letters: "t", position: .middle),
                      SoundBookWord(id: "chat", drawing: "fr.minouche", text: "cat", ipa: "kæt", wagons: ["cat"], targetWagon: 0, letters: "t", position: .end),
                      SoundBookWord(id: "cadeau", drawing: "mot.cadeau", text: "gift", ipa: "ɡɪft", wagons: ["gift"], targetWagon: 0, letters: "t", position: .end),
                      SoundBookWord(id: "nid", drawing: "mot.nid", text: "nest", ipa: "nɛst", wagons: ["nest"], targetWagon: 0, letters: "t", position: .end),
                      SoundBookWord(id: "assiette", drawing: "en.dish", text: "plate", ipa: "pleɪt", wagons: ["plate"], targetWagon: 0, letters: "t", position: .end),
                      SoundBookWord(id: "lapin", drawing: "mot.lapin", text: "rabbit", ipa: "ˈɹæ.bɪt", wagons: ["rab", "bit"], targetWagon: 1, letters: "t", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "d", label: "d",
                  image: "The drum: dum, dum! Like “t”, but the throat buzzes.",
                  game: "Tap a pot like a drum: dum, dum, dum.", words: [
                      SoundBookWord(id: "biche", drawing: "fr.biche", text: "deer", ipa: "dɪɹ", wagons: ["deer"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "chien", drawing: "fr.caniche", text: "dog", ipa: "dɔɡ", wagons: ["dog"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "niche", drawing: "lieu.niche", text: "doghouse", ipa: "ˈdɔɡ.haʊs", wagons: ["dog", "house"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "dauphin", drawing: "mot.dauphin", text: "dolphin", ipa: "ˈdɑl.fɪn", wagons: ["dol", "phin"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "canard", drawing: "mot.canard", text: "duck", ipa: "dʌk", wagons: ["duck"], targetWagon: 0, letters: "d", position: .start),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "ˈkɹɑ.kə.daɪl", wagons: ["croc", "o", "dile"], targetWagon: 2, letters: "d", position: .middle),
                      SoundBookWord(id: "radis", drawing: "en.radish", text: "radish", ipa: "ˈɹæ.dɪʃ", wagons: ["ra", "dish"], targetWagon: 1, letters: "d", position: .middle),
                      SoundBookWord(id: "araignee", drawing: "mot.araignee", text: "spider", ipa: "ˈspaɪ.dɚ", wagons: ["spi", "der"], targetWagon: 1, letters: "d", position: .middle),
                      SoundBookWord(id: "lit", drawing: "lieu.lit", text: "bed", ipa: "bɛd", wagons: ["bed"], targetWagon: 0, letters: "d", position: .end),
                      SoundBookWord(id: "oiseau", drawing: "fr.perruche", text: "bird", ipa: "bɝd", wagons: ["bird"], targetWagon: 0, letters: "d", position: .end),
                      SoundBookWord(id: "pain", drawing: "mot.pain", text: "bread", ipa: "bɹɛd", wagons: ["bread"], targetWagon: 0, letters: "d", position: .end),
                      SoundBookWord(id: "nuage", drawing: "mot.nuage", text: "cloud", ipa: "klaʊd", wagons: ["cloud"], targetWagon: 0, letters: "d", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "k", label: "k",
                  image: "The crow: caw, caw! The back of the tongue closes, then opens.",
                  game: "Hide a toy; say “caw caw” louder as someone gets closer.", words: [
                      SoundBookWord(id: "cactus", drawing: "fr.cactus", text: "cactus", ipa: "ˈkæk.təs", wagons: ["cac", "tus"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "voiture", drawing: "lieu.voiture", text: "car", ipa: "kɑɹ", wagons: ["car"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "carrosse", drawing: "fr.carrosse", text: "carriage", ipa: "ˈkæ.ɹɪdʒ", wagons: ["car", "riage"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "chat", drawing: "fr.minouche", text: "cat", ipa: "kæt", wagons: ["cat"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "nuage", drawing: "mot.nuage", text: "cloud", ipa: "klaʊd", wagons: ["cloud"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "peigne", drawing: "mot.peigne", text: "comb", ipa: "koʊm", wagons: ["comb"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "vache", drawing: "fr.vache", text: "cow", ipa: "kaʊ", wagons: ["cow"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "ˈkɹɑ.kə.daɪl", wagons: ["croc", "o", "dile"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "tasse", drawing: "fr.tasse", text: "cup", ipa: "kʌp", wagons: ["cup"], targetWagon: 0, letters: "c", position: .start),
                      SoundBookWord(id: "cle", drawing: "mot.cle", text: "key", ipa: "ki", wagons: ["key"], targetWagon: 0, letters: "k", position: .start),
                      SoundBookWord(id: "boite", drawing: "lieu.boite", text: "box", ipa: "bɑks", wagons: ["box"], targetWagon: 0, letters: "x", position: .middle),
                      SoundBookWord(id: "cirque", drawing: "en.circus", text: "circus", ipa: "ˈsɝ.kəs", wagons: ["cir", "cus"], targetWagon: 1, letters: "c", position: .middle),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "ice cream", ipa: "ˈaɪs.kɹim", wagons: ["ice", "cream"], targetWagon: 1, letters: "c", position: .middle),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "pencil case", ipa: "ˈpɛn.səl.keɪs", wagons: ["pen", "cil", "case"], targetWagon: 2, letters: "c", position: .middle),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police car", ipa: "pə.ˈlis.kɑɹ", wagons: ["po", "lice", "car"], targetWagon: 2, letters: "c", position: .middle),
                      SoundBookWord(id: "canard", drawing: "mot.canard", text: "duck", ipa: "dʌk", wagons: ["duck"], targetWagon: 0, letters: "ck", position: .end),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "motorbike", ipa: "ˈmoʊ.tɚ.baɪk", wagons: ["mo", "tor", "bike"], targetWagon: 2, letters: "k", position: .end),
                      SoundBookWord(id: "camion", drawing: "mot.camion", text: "truck", ipa: "tɹʌk", wagons: ["truck"], targetWagon: 0, letters: "ck", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "ɡ", label: "g",
                  image: "The frog: ribbit… g-g-g! Like “k”, but the throat buzzes.",
                  game: "Hop like frogs, saying “g” at each hop.", words: [
                      SoundBookWord(id: "cadeau", drawing: "mot.cadeau", text: "gift", ipa: "ɡɪft", wagons: ["gift"], targetWagon: 0, letters: "g", position: .start),
                      SoundBookWord(id: "oie", drawing: "en.goose", text: "goose", ipa: "ɡus", wagons: ["goose"], targetWagon: 0, letters: "g", position: .start),
                      SoundBookWord(id: "niche", drawing: "lieu.niche", text: "doghouse", ipa: "ˈdɔɡ.haʊs", wagons: ["dog", "house"], targetWagon: 0, letters: "g", position: .middle),
                      SoundBookWord(id: "sac", drawing: "mot.sac", text: "bag", ipa: "bæɡ", wagons: ["bag"], targetWagon: 0, letters: "g", position: .end),
                      SoundBookWord(id: "chien", drawing: "fr.caniche", text: "dog", ipa: "dɔɡ", wagons: ["dog"], targetWagon: 0, letters: "g", position: .end),
                      SoundBookWord(id: "buche", drawing: "fr.buche", text: "log", ipa: "lɔɡ", wagons: ["log"], targetWagon: 0, letters: "g", position: .end),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "slug", ipa: "slʌɡ", wagons: ["slug"], targetWagon: 0, letters: "g", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "m", label: "m",
                  image: "Yummy: mmm! Lips closed, it tickles.",
                  game: "At mealtime, say “mmm” after each favourite bite.", words: [
                      SoundBookWord(id: "lune", drawing: "mot.lune", text: "moon", ipa: "mun", wagons: ["moon"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "elan", drawing: "en.moose", text: "moose", ipa: "mus", wagons: ["moose"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "moto", drawing: "mot.moto", text: "motorbike", ipa: "ˈmoʊ.tɚ.baɪk", wagons: ["mo", "tor", "bike"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "souris", drawing: "en.mouse", text: "mouse", ipa: "maʊs", wagons: ["mouse"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "bouche", drawing: "fr.bouche", text: "mouth", ipa: "maʊθ", wagons: ["mouth"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "champignon", drawing: "mot.champignon", text: "mushroom", ipa: "ˈmʌʃ.ɹum", wagons: ["mush", "room"], targetWagon: 0, letters: "m", position: .start),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "umbrella", ipa: "ʌm.ˈbɹɛ.lə", wagons: ["um", "brel", "la"], targetWagon: 0, letters: "m", position: .middle),
                      SoundBookWord(id: "peigne", drawing: "mot.peigne", text: "comb", ipa: "koʊm", wagons: ["comb"], targetWagon: 0, letters: "m", position: .end),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "ice cream", ipa: "ˈaɪs.kɹim", wagons: ["ice", "cream"], targetWagon: 1, letters: "m", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "n", label: "n",
                  image: "The buzzing nose: nnn! Tongue behind the teeth, air through the nose.",
                  game: "Gently pinch your nose while saying nnn: it stops! What happened?", words: [
                      SoundBookWord(id: "nid", drawing: "mot.nid", text: "nest", ipa: "nɛst", wagons: ["nest"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "nez", drawing: "mot.nez", text: "nose", ipa: "noʊz", wagons: ["nose"], targetWagon: 0, letters: "n", position: .start),
                      SoundBookWord(id: "banane", drawing: "mot.banane", text: "banana", ipa: "bə.ˈnæ.nə", wagons: ["ba", "na", "na"], targetWagon: 1, letters: "n", position: .middle),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "pencil case", ipa: "ˈpɛn.səl.keɪs", wagons: ["pen", "cil", "case"], targetWagon: 0, letters: "n", position: .middle),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princess", ipa: "ˈpɹɪn.sɛs", wagons: ["prin", "cess"], targetWagon: 0, letters: "n", position: .middle),
                      SoundBookWord(id: "os", drawing: "fr.os", text: "bone", ipa: "boʊn", wagons: ["bone"], targetWagon: 0, letters: "n", position: .end),
                      SoundBookWord(id: "dauphin", drawing: "mot.dauphin", text: "dolphin", ipa: "ˈdɑl.fɪn", wagons: ["dol", "phin"], targetWagon: 1, letters: "n", position: .end),
                      SoundBookWord(id: "lune", drawing: "mot.lune", text: "moon", ipa: "mun", wagons: ["moon"], targetWagon: 0, letters: "n", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "l", label: "l",
                  image: "Sing “la, la, la”: the tongue lifts behind the top teeth.",
                  game: "Sing a nursery rhyme on “la, la, la”, then “lo, lo, lo”.", words: [
                      SoundBookWord(id: "buche", drawing: "fr.buche", text: "log", ipa: "lɔɡ", wagons: ["log"], targetWagon: 0, letters: "l", position: .start),
                      SoundBookWord(id: "lou", drawing: "perso.lou", text: "Lou", ipa: "lu", wagons: ["Lou"], targetWagon: 0, letters: "L", position: .start),
                      SoundBookWord(id: "papillon", drawing: "mot.papillon", text: "butterfly", ipa: "ˈbʌ.tɚ.flaɪ", wagons: ["but", "ter", "fly"], targetWagon: 2, letters: "l", position: .middle),
                      SoundBookWord(id: "nuage", drawing: "mot.nuage", text: "cloud", ipa: "klaʊd", wagons: ["cloud"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "dauphin", drawing: "mot.dauphin", text: "dolphin", ipa: "ˈdɑl.fɪn", wagons: ["dol", "phin"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "mouche", drawing: "fr.mouche", text: "fly", ipa: "flaɪ", wagons: ["fly"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "trousse", drawing: "fr.trousse", text: "pencil case", ipa: "ˈpɛn.səl.keɪs", wagons: ["pen", "cil", "case"], targetWagon: 1, letters: "l", position: .middle),
                      SoundBookWord(id: "assiette", drawing: "en.dish", text: "plate", ipa: "pleɪt", wagons: ["plate"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police car", ipa: "pə.ˈlis.kɑɹ", wagons: ["po", "lice", "car"], targetWagon: 1, letters: "l", position: .middle),
                      SoundBookWord(id: "limace", drawing: "fr.limace", text: "slug", ipa: "slʌɡ", wagons: ["slug"], targetWagon: 0, letters: "l", position: .middle),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "umbrella", ipa: "ʌm.ˈbɹɛ.lə", wagons: ["um", "brel", "la"], targetWagon: 2, letters: "l", position: .middle),
                      SoundBookWord(id: "pomme", drawing: "mot.pomme", text: "apple", ipa: "ˈæ.pəl", wagons: ["ap", "ple"], targetWagon: 1, letters: "l", position: .end),
                      SoundBookWord(id: "balle", drawing: "en.tennis", text: "ball", ipa: "bɔl", wagons: ["ball"], targetWagon: 0, letters: "ll", position: .end),
                      SoundBookWord(id: "cloche", drawing: "fr.cloche", text: "bell", ipa: "bɛl", wagons: ["bell"], targetWagon: 0, letters: "ll", position: .end),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "ˈkɹɑ.kə.daɪl", wagons: ["croc", "o", "dile"], targetWagon: 2, letters: "l", position: .end),
                      SoundBookWord(id: "puzzle", drawing: "en.piece", text: "puzzle", ipa: "ˈpʌ.zəl", wagons: ["puz", "zle"], targetWagon: 1, letters: "l", position: .end),
                      SoundBookWord(id: "table", drawing: "lieu.table", text: "table", ipa: "ˈteɪ.bəl", wagons: ["ta", "ble"], targetWagon: 1, letters: "l", position: .end),
                  ]),
        SoundBook(locale: "en-US", sound: "ɹ", label: "r",
                  image: "The lion's growl: rrr (lips a little round).",
                  game: "Be lions waking up: a soft rrr, then louder.", words: [
                      SoundBookWord(id: "lapin", drawing: "mot.lapin", text: "rabbit", ipa: "ˈɹæ.bɪt", wagons: ["rab", "bit"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "radis", drawing: "en.radish", text: "radish", ipa: "ˈɹæ.dɪʃ", wagons: ["ra", "dish"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "coq", drawing: "mot.coq", text: "rooster", ipa: "ˈɹus.tɚ", wagons: ["roos", "ter"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "rose", drawing: "mot.rose", text: "rose", ipa: "ɹoʊz", wagons: ["rose"], targetWagon: 0, letters: "r", position: .start),
                      SoundBookWord(id: "fleche", drawing: "fr.fleche", text: "arrow", ipa: "ˈæ.ɹoʊ", wagons: ["ar", "row"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "pain", drawing: "mot.pain", text: "bread", ipa: "bɹɛd", wagons: ["bread"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "brosse", drawing: "fr.brosse", text: "brush", ipa: "bɹʌʃ", wagons: ["brush"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "carrosse", drawing: "fr.carrosse", text: "carriage", ipa: "ˈkæ.ɹɪdʒ", wagons: ["car", "riage"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "crocodile", drawing: "mot.crocodile", text: "crocodile", ipa: "ˈkɹɑ.kə.daɪl", wagons: ["croc", "o", "dile"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "glace", drawing: "fr.glace", text: "ice cream", ipa: "ˈaɪs.kɹim", wagons: ["ice", "cream"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "champignon", drawing: "mot.champignon", text: "mushroom", ipa: "ˈmʌʃ.ɹum", wagons: ["mush", "room"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "autruche", drawing: "fr.autruche", text: "ostrich", ipa: "ˈɑ.stɹɪtʃ", wagons: ["os", "trich"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "princesse", drawing: "fr.princesse", text: "princess", ipa: "ˈpɹɪn.sɛs", wagons: ["prin", "cess"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "arbre", drawing: "lieu.arbre", text: "tree", ipa: "tɹi", wagons: ["tree"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "camion", drawing: "mot.camion", text: "truck", ipa: "tɹʌk", wagons: ["truck"], targetWagon: 0, letters: "r", position: .middle),
                      SoundBookWord(id: "parapluie", drawing: "mot.parapluie", text: "umbrella", ipa: "ʌm.ˈbɹɛ.lə", wagons: ["um", "brel", "la"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "zebre", drawing: "mot.zebre", text: "zebra", ipa: "ˈzi.bɹə", wagons: ["ze", "bra"], targetWagon: 1, letters: "r", position: .middle),
                      SoundBookWord(id: "voiture", drawing: "lieu.voiture", text: "car", ipa: "kɑɹ", wagons: ["car"], targetWagon: 0, letters: "r", position: .end),
                      SoundBookWord(id: "biche", drawing: "fr.biche", text: "deer", ipa: "dɪɹ", wagons: ["deer"], targetWagon: 0, letters: "r", position: .end),
                      SoundBookWord(id: "police", drawing: "fr.police", text: "police car", ipa: "pə.ˈlis.kɑɹ", wagons: ["po", "lice", "car"], targetWagon: 2, letters: "r", position: .end),
                  ]),
    ]
}
